---
- name: Create templates for each host
  template:
    src: templates/template.j2
    dest: "configs/{{ item.hostname }}.conf"
  loop: "{{ inventory_hosts }}"
  loop_control:
    label: "{{ item.hostname }}"


