# .github/workflows/configure.yml
name: Configure Servers

on:
  workflow_dispatch:
    inputs:
      ip:
        description: "IP address"
        required: true
      hostname:
        description: "Hostname (optional)"
        required: false
      location:
        description: "Location (optional)"
        required: false
      port:
        description: "Port"
        required: true

jobs:
  group1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Ansible for group1
        uses: ansible/ansible-lint-action@v6
        with:
          args: >
            ansible-playbook playbook_group1.yml
            --extra-vars "ip=${{ github.event.inputs.ip }}
                          hostname=${{ github.event.inputs.hostname }}"

  group2:
    runs-on: ubuntu-latest
    needs: group1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Ansible for group2
        uses: ansible/ansible-lint-action@v6
        with:
          args: >
            ansible-playbook playbook_group2.yml
            --extra-vars "location=${{ github.event.inputs.location }}
                          port=${{ github.event.inputs.port }}"
